language: python
python:
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create --name linter-env python=$TRAVIS_PYTHON_VERSION black flake8 flake8-builtins flake8-black flake8-bugbear flake8-comprehensions flake8-isort
script:
  - conda activate linter-env
  - flake8 .
